name: builder
on:
  push:
    branches:
      - 'main'
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - 
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: cloudynes
          password: ${{ secrets.GITHUB_TOKEN }}
      - 
        name: Download keywind theme
        run: |
          rm -rf keywind && git clone https://github.com/lukin/keywind.git keywind
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/cloudynes/keycloak:latest
